[package]
name = "suds_util"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.1.0"
quick-xml = "0.22.0"
reqwest = { version = "0.11.6", features = ["blocking"] }
